(defun new-test-case ()
  "Creates new test case formatting."
  (interactive)
  (setq buf (current-buffer))
  (goto-char (point-max))
  (when (/= (point) (point-min))
      (terpri buf)
      (terpri buf)
    )
  (prin1 '******************************** buf)
  (terpri buf)
  (prin1 'Название: buf)
  (save-excursion
    (terpri buf)
    (prin1 '******************************** buf)
    (terpri buf)
    (prin1 'Условия: buf)
    )
  )
